/** Element ids, CSS class names and data attributes of index.html / style.css, plus DOM helpers. */

export const $ = (id) => document.getElementById(id);

/** HTML-escapes a value for insertion in markup. */
export const esc = (s) => String(s)
  .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');

export const ID = {
  FILE_MENU_BUTTON: 'fileMenuBtn',
  FILE_MENU: 'fileMenu',
  MENU_OPEN: 'menuOpen',
  MENU_OPEN_FOLDER: 'menuOpenFolder',
  MENU_NEW_WORKSPACE: 'menuNewWorkspace',
  MENU_OPEN_WORKSPACE: 'menuOpenWorkspace',
  MENU_CLOSE_WORKSPACE: 'menuCloseWorkspace',
  MENU_SAVE_WORKSPACE: 'menuSaveWorkspace',
  MENU_NEW_TAB: 'menuNewTab',
  MENU_CLOSE: 'menuClose',
  MENU_CLOSE_ALL: 'menuCloseAll',
  MENU_QUIT: 'menuQuit',
  SETTINGS_MENU_BUTTON: 'settingsMenuBtn',
  SETTINGS_MENU: 'settingsMenu',
  MENU_AUTO_STOP: 'menuAutoStop',
  MENU_THEME: 'menuTheme',
  HELP_MENU_BUTTON: 'helpMenuBtn',
  HELP_MENU: 'helpMenu',
  MENU_ABOUT: 'menuAbout',
  MENU_VALIDATE: 'menuValidate',
  VALIDATE_INPUT: 'validateInput',
  VALIDATE_DIALOG: 'validateDialog',
  VALIDATE_TITLE: 'validateTitle',
  VALIDATE_SUMMARY: 'validateSummary',
  VALIDATE_PROBLEMS: 'validateProblems',
  VALIDATE_CLOSE: 'validateClose',
  ABOUT_DIALOG: 'aboutDialog',
  ABOUT_VERSION: 'aboutVersion',
  ABOUT_JAVA: 'aboutJava',
  ABOUT_LOG: 'aboutLog',
  ABOUT_PROJECT_LINK: 'aboutProjectLink',
  ABOUT_LICENSE_LINK: 'aboutLicenseLink',
  ABOUT_CLOSE: 'aboutClose',
  FILE_NAME: 'fileName',
  BUSY: 'busy',
  BUSY_LABEL: 'busyLabel',
  EXPORT_BUTTON: 'exportBtn',
  SHOW_BUILTINS: 'showBuiltins',
  LANGUAGE: 'language',
  TABS: 'tabs',
  WORKSPACE_BAR: 'workspaceBar',
  WORKSPACES: 'workspaces',
  NEW_TAB_BUTTON: 'newTabBtn',
  COMPARE_BUTTON: 'compareBtn',
  COMPARE_HINT: 'compareHint',
  COMPARE: 'compare',
  COMPARE_TITLE: 'compareTitle',
  COMPARE_SUMMARY: 'compareSummary',
  COMPARE_LEGEND: 'compareLegend',
  COMPARE_CLOSE: 'compareClose',
  COMPARE_BUSINESS_ONLY: 'businessOnly',
  COMPARE_DIFF_ONLY: 'diffOnly',
  COMPARE_TABLE: 'compareTable',
  SIDEBAR: 'sidebar',
  FILES: 'files',
  FILES_CONTENT: 'filesContent',
  FILES_TOGGLE: 'filesToggle',
  FILES_COUNT: 'filesCount',
  FILES_EXPAND_ALL: 'filesExpandAll',
  FILES_COLLAPSE_ALL: 'filesCollapseAll',
  OBJECTS_EXPAND_ALL: 'objectsExpandAll',
  GRAPH_LEGEND: 'graphLegend',
  EXPORT_SVG_BUTTON: 'exportSvgBtn',
  OBJECTS_COLLAPSE_ALL: 'objectsCollapseAll',
  COMPARE_EXPAND_ALL: 'compareExpandAll',
  COMPARE_COLLAPSE_ALL: 'compareCollapseAll',
  SCHEMA_INFO: 'schemaInfo',
  SCHEMA_INFO_CONTENT: 'schemaInfoContent',
  SCHEMA_INFO_TOGGLE: 'schemaInfoToggle',
  SEARCH: 'search',
  SEARCH_CLEAR: 'searchClear',
  NODE_LIST: 'nodeList',
  EMPTY: 'empty',
  GRAPH: 'graph',
  BACK_BUTTON: 'backBtn',
  GRAPH_TITLE: 'graphTitle',
  TWO_LEVELS: 'twoLevels',
  GRAPH_CANVAS: 'graphCanvas',
  TEXT: 'text',
  TEXT_FIND: 'textFind',
  TEXT_FIND_INPUT: 'textFindInput',
  TEXT_FIND_COUNT: 'textFindCount',
  TEXT_FIND_PREV: 'textFindPrev',
  TEXT_FIND_NEXT: 'textFindNext',
  TEXT_FIND_CLOSE: 'textFindClose',
  DETAILS: 'details',
  DETAILS_CONTENT: 'detailsContent',
  DETAILS_TOGGLE: 'detailsToggle',
  DROP_OVERLAY: 'dropOverlay',
  TOAST: 'toast',
  FILE_INPUT: 'fileInput',
  FOLDER_INPUT: 'folderInput',
};

export const CLS = {
  HIDDEN: 'hidden',
  ACTIVE: 'active',
  /** A menu entry that is a switch, currently on (its .check mark is shown). */
  CHECKED: 'checked',
  SELECTED: 'selected',
  COLLAPSED: 'collapsed',
  VIEW: 'view',
  VIEW_TAB: 'tab',
  EMPTY_BOX: 'emptybox',
  BIG: 'big',
  // document tabs
  DOC_TAB: 'dtab',
  DOC_TAB_NAME: 'tname',
  DOC_TAB_CLOSE: 'tclose',
  COMPARE_TAB: 'ctab',
  WORKSPACE_GROUP: 'wsgroup',
  WORKSPACE_NAME: 'wsname',
  WORKSPACE_CLOSE: 'wsclose',
  WORKSPACE_OPEN: 'wsopen',
  // comparison
  COMPARE_ROW: 'crow',
  COMPARE_DETAIL: 'cdetail',
  COMPARE_NAME: 'cname',
  COMPARE_PATH: 'cpath',
  COMPARE_STATUS: 'cstatus',
  COMPARE_MODEL: 'cmodel',
  LEGEND_ENTRY: 'lg',
  DIFF_SIDES: 'csides',
  DIFF_SIDE: 'cside',
  EXPANDABLE: 'expandable',
  OPEN: 'open',
  DIFF: 'diff',
  EQUAL: 'eq',
  CHANGE: 'chg',
  DELETED: 'del',
  INSERTED: 'ins',
  MOVED: 'mov',
  FOLD: 'fold',
  // sidebar
  GROUP_HEADER: 'group-h',
  GROUP_ITEMS: 'group-items',
  ITEM: 'item',
  NO_MATCH: 'nomatch',
  DIR: 'dir',
  FILE: 'file',
  OBJECT: 'obj',
  OBJECTS: 'objects',
  EXPANDER: 'expander',
  EMPTY: 'empty',
  /** The row of the Files panel counting the files still being parsed. */
  PARSING: 'parsing',
  /** Why a searched object is listed when its name does not match (the member or the documentation that does). */
  WHY: 'why',
  /** The rows of the validation dialog. */
  PROBLEM: 'problem',
  VALID: 'valid',
  INVALID: 'invalid',
  DOT: 'dot',
  COUNT: 'count',
  // graph (SVG)
  NODE: 'node',
  CENTER: 'center',
  EDGE: 'edge',
  EDGE_LABEL: 'edge-label',
  EDGE_LABEL_BG: 'edge-label-bg',
  NODE_NAME: 'name',
  NODE_KIND: 'kind',
  LINK_NAME: 'link-name',
  STRUCTURAL: 'structural',
  CARDINALITY: 'card',
  OPTIONAL: 'optional',
  /** An edge to a base type (extends / restricts). */
  DERIVATION: 'derivation',
  /** The arrowhead of an edge (a marker path), coloured by the stylesheet. */
  ARROW_HEAD: 'arrow-head',
  /** On the legend: the shown file is a WSDL (its kinds are listed). */
  WSDL: 'wsdl',
  // details
  BADGE: 'badge',
  META: 'meta',
  DOC: 'doc',
  /** A row of the enumeration of the selected object in the details panel. */
  VALUE: 'value',
  VALUE_DOC: 'value-doc',
  LINK: 'link',
  LINK_LABEL: 'lbl',
  LINK_TARGET: 'tgt',
  // text view
  LINE: 'line',
  LINE_DECLARATION: 'decl',
  LINE_HIGHLIGHT: 'hl',
  /** A line holding the text of the find bar; the one the bar is at. */
  FOUND: 'found',
  CURRENT: 'current',
  LINE_NUMBER: 'ln',
  CODE: 'code',
};

/** Classes of the syntax-highlighted XML tokens (colours in style.css). */
export const TOKEN_CLS = { COMMENT: 'c', PI: 'pi', VALUE: 'v', TAG: 't', ATTRIBUTE: 'a' };

/** data-* attribute names (without the "data-" prefix, as in element.dataset). */
export const DATA = {
  ID: 'id',
  TAB: 'tab',
  KIND: 'kind',
  LINE: 'line',
  LINE_NUMBER: 'n',
  TAB_INDEX: 'i',
  WORKSPACE_INDEX: 'ws',
  DIR: 'dir',
  FILE: 'file',
  ROW_INDEX: 'row',
  VIEW: 'view',
};
export const dataAttr = (name, value) => ' data-' + name + '="' + esc(value) + '"';

/** Ids inside the graph SVG. */
export const SVG_ID = { ARROW: 'arrow', DERIVATION_ARROW: 'arrowDerivation' };

export const selector = (cls) => '.' + cls;
