/** Keys of the texts in i18n/<language>.json (see i18n.js). Constants ending with '.' are prefixes completed by a node kind. */
export const MSG = {
  APP_TITLE: 'app.title',
  /** The language's name in its own language, in each i18n file. */
  LANGUAGE_NAME: 'language.name',
  LANGUAGE_TITLE: 'language.title',
  APP_TITLE_WITH_FILE: 'app.titleWithFile',
  STATUS_NO_FILE: 'status.noFile',
  ABOUT_VERSION: 'about.version',
  ABOUT_JAVA: 'about.java',
  ABOUT_LOG: 'about.log',

  TAB_UNTITLED: 'tab.untitled',
  TAB_CLOSE: 'tab.close',
  WORKSPACE_UNTITLED: 'workspace.untitled',
  WORKSPACE_CLOSE: 'workspace.close',
  WORKSPACE_SELECT_HINT: 'workspace.selectHint',
  COMPARE_NEED_TWO: 'compare.needTwo',
  COMPARE_TAB: 'compare.tab',
  COMPARE_FILE_TAB: 'compare.fileTab',
  COMPARE_FILE_TITLE: 'compare.fileTitle',
  COMPARE_OPEN_TAB: 'compare.openTab',
  COMPARE_OPEN_TAB_LABEL: 'compare.openTab.label',
  COMPARE_TITLE: 'compare.title',
  COMPARE_SUMMARY: 'compare.summary',
  COMPARE_FILE: 'compare.file',
  COMPARE_STATUS: 'compare.status',
  COMPARE_SAME: 'compare.same',
  COMPARE_DIFFERENT: 'compare.different',
  COMPARE_MOVED: 'compare.moved',
  COMPARE_LEGEND_MOVED: 'compare.legend.moved',
  COMPARE_MOVED_TO: 'compare.movedTo',
  COMPARE_MOVED_FROM: 'compare.movedFrom',
  COMPARE_ONLY_IN: 'compare.onlyIn',
  COMPARE_SAME_MODEL: 'compare.sameModel',
  COMPARE_DECLARATIONS_ONLY_IN: 'compare.declarationsOnlyIn',
  COMPARE_LINKS_ONLY_IN: 'compare.linksOnlyIn',
  COMPARE_TEXT_TOO_LARGE: 'compare.textTooLarge',
  COMPARE_IDENTICAL_LINES_ONE: 'compare.identicalLines.one',
  COMPARE_IDENTICAL_LINES_OTHER: 'compare.identicalLines.other',

  KIND_PREFIX: 'kind.',
  GROUP_PREFIX: 'group.',

  FILES_COLLAPSE: 'files.collapse',
  FILES_NOT_A_SCHEMA: 'files.notASchema',
  FILES_PARSING_ONE: 'files.parsing.one',
  FILES_PARSING_OTHER: 'files.parsing.other',
  FILES_PARSING_TITLE: 'files.parsing.title',
  SEARCH_IN_DOC: 'search.inDoc',
  SEARCH_IN_XPATH: 'search.inXpath',
  MENU_THEME_LIGHT: 'menu.theme.light',
  MENU_THEME_DARK: 'menu.theme.dark',
  OPEN_ALL_CONFIRM: 'openAll.confirm',
  OPEN_ALL_DONE: 'openAll.done',
  VALIDATE_NEEDS_LOCATION: 'validate.needsLocation',
  VALIDATE_VALID: 'validate.valid',
  VALIDATE_INVALID_ONE: 'validate.invalid.one',
  VALIDATE_INVALID_OTHER: 'validate.invalid.other',
  VALIDATE_TRUNCATED: 'validate.truncated',
  VALIDATE_WHERE: 'validate.where',
  BUSY_VALIDATING: 'busy.validating',
  BUSY_OPENING: 'busy.opening',
  BUSY_READING_FOLDER: 'busy.readingFolder',
  BUSY_WORKSPACE: 'busy.workspace',
  BUSY_PARSING: 'busy.parsing',
  BUSY_LINKED: 'busy.linked',
  FILES_OPEN_AS_WORKSPACE: 'files.openAsWorkspace',
  FILES_EXPAND: 'files.expand',
  INFO_TITLE: 'info.title',
  INFO_COLLAPSE: 'info.collapse',
  INFO_EXPAND: 'info.expand',
  INFO_TARGET_NAMESPACE: 'info.targetNamespace',
  INFO_NONE: 'info.none',
  INFO_UNKNOWN_LOCATION: 'info.unknownLocation',
  INFO_COUNTS: 'info.counts',
  LIST_NO_MATCH: 'list.noMatch',

  GRAPH_NODE_TITLE: 'graph.nodeTitle',
  GRAPH_KIND_IN_FILE: 'graph.kindInFile',

  DETAILS_SHOW_IN_TEXT: 'details.showInText',
  DETAILS_NO_DECLARATION: 'details.noDeclaration',
  DETAILS_LINKS_OUT: 'details.linksOut',
  DETAILS_USED_BY: 'details.usedBy',
  DETAILS_VALUES: 'details.values',
  DETAILS_XPATH: 'details.xpath',
  DETAILS_NONE: 'details.none',
  DETAILS_COLLAPSE: 'details.collapse',
  DETAILS_EXPAND: 'details.expand',
  TEXT_SELECT: 'text.select',

  SERVER_UNREACHABLE: 'toast.serverUnreachable',
  SERVER_ERROR: 'toast.serverError',
  DIALOGS_UNAVAILABLE: 'dialogs.unavailable',
  WORKSPACE_SAVED: 'workspace.saved',
  WORKSPACE_NOT_SAVED: 'workspace.notSaved',
  WORKSPACE_EMPTY: 'workspace.empty',
  WORKSPACE_LOADED_ONE: 'workspace.loaded.one',
  WORKSPACE_LOADED_OTHER: 'workspace.loaded.other',
  WORKSPACE_MISSING: 'workspace.missing',
  WORKSPACE_LISTED: 'workspace.listed',
  WORKSPACE_ALREADY_OPEN: 'workspace.alreadyOpen',
  LINKED_OPENED_ONE: 'linked.opened.one',
  LINKED_OPENED_OTHER: 'linked.opened.other',
  LINKED_LISTED_ONE: 'linked.listed.one',
  LINKED_LISTED_OTHER: 'linked.listed.other',
  CANNOT_PARSE: 'toast.cannotParse',
  CANNOT_STOP: 'toast.cannotStop',
  SETTINGS_AUTO_STOP_ON: 'settings.autoStop.on',
  SETTINGS_AUTO_STOP_OFF: 'settings.autoStop.off',
  QUIT_CONFIRM: 'quit.confirm',
  QUIT_STOPPED_TITLE: 'quit.stoppedTitle',
  QUIT_STOPPED_HINT: 'quit.stoppedHint',

  EXTERNAL_NO_LOCATION: 'external.noLocation',
  EXTERNAL_MISSING: 'external.missing',
  EXTERNAL_NOT_FOUND_IN: 'external.notFoundIn',
  EXTERNAL_NOT_FOUND: 'external.notFound',
  EXTERNAL_CHOOSE_FILE: 'external.chooseFile',

  FOLDER_OPENED_ONE: 'folder.opened.one',
  FOLDER_OPENED_OTHER: 'folder.opened.other',
  FOLDER_EMPTY: 'folder.empty',
  FOLDER_TRUNCATED: 'folder.truncated',
  FOLDER_LISTED: 'folder.listed',

  EXPORT_SELECT_FIRST: 'export.selectFirst',
  EXPORT_RENDER_FAILED: 'export.renderFailed',
  EXPORT_PNG_FAILED: 'export.pngFailed',
  EXPORT_TEXT_TRUNCATED: 'export.textTruncated',
};
